version: "3.7"

services:
  db:
    container_name: "db"
    image: "postgres:14.7-alpine"
    restart: always

    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  nbp:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "PATH=.venv/bin:$$PATH &&
         python manage.py makemigrations &&
         python manage.py migrate &&
         python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db