# Generated by Django 4.1.7 on 2023-03-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nbp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Question",
        ),
    ]
