# Generated by Django 4.1.7 on 2023-03-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nbp", "0002_delete_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRateA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("currency", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=3)),
                ("mid", models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
