# Generated by Django 4.1.7 on 2023-03-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nbp", "0003_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExchangeRateA",
            new_name="ExchangeRate",
        ),
    ]
