# Generated by Django 4.1.7 on 2023-03-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nbp", "0004_rename_exchangeratea_exchangerate"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exchangerate",
            unique_together={("date", "currency", "code", "mid")},
        ),
    ]
